<div>
    <x-admin.page-header title="Kategori" description="Atur klasifikasi pemasukan dan pengeluaran per keluarga.">
        <x-slot:actions><button type="button" class="admin-button admin-button-primary" wire:click="openCreate">Tambah kategori</button></x-slot:actions>
    </x-admin.page-header>
    <div class="admin-card overflow-hidden">
        <div class="grid gap-3 border-b border-slate-100 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_12rem] sm:px-6"><div><label for="category-search" class="mb-1 block text-xs font-bold text-slate-700">Cari kategori</label><input id="category-search" wire:model.live.debounce.300ms="search" class="admin-input" placeholder="Nama kategori"></div><div><label for="category-type" class="mb-1 block text-xs font-bold text-slate-700">Tipe</label><select id="category-type" wire:model.live="filterType" class="admin-select"><option value="">Semua tipe</option><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select></div></div>
        <div class="flex items-center justify-between border-b border-slate-100 px-4 py-4 sm:px-6"><div><h2 class="text-base font-extrabold text-slate-900">Semua kategori</h2><p class="mt-1 text-xs font-semibold text-slate-600">{{ $categories->total() }} kategori ditemukan.</p></div><span wire:loading class="text-xs font-bold text-emerald-700">Memuat...</span></div>
        <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Nama</th><th>Tipe</th><th>Keluarga</th><th>Induk</th><th>Ikon</th><th>Aksi</th></tr></thead><tbody>
        @forelse($categories as $category)
            <tr><td class="font-bold text-slate-800">{{ $category->name }}</td><td><span @class(['rounded-md px-2 py-1 text-xs font-bold', 'bg-emerald-50 text-emerald-800' => $category->type === 'income', 'bg-rose-50 text-rose-800' => $category->type === 'expense'])>{{ $category->type === 'income' ? 'Pemasukan' : 'Pengeluaran' }}</span></td><td class="text-sm text-slate-700">{{ $category->household?->name ?? '-' }}</td><td class="text-sm text-slate-700">{{ $category->parent?->name ?? '-' }}</td><td class="text-sm text-slate-700">{{ $category->icon ?: '-' }}</td><td><div class="flex flex-wrap gap-2"><button type="button" class="admin-button admin-button-secondary" wire:click="edit({{ $category->id }})">Edit</button><button type="button" class="admin-button admin-button-danger" wire:click="askDelete({{ $category->id }})">Hapus</button></div></td></tr>
        @empty
            <tr><td colspan="6" class="px-4 py-10 text-center text-sm font-semibold text-slate-600">Tidak ada kategori yang cocok. Tambahkan kategori atau ubah filter.</td></tr>
        @endforelse
        </tbody></table></div><x-admin.pagination :items="$categories" />
    </div>
    @if($showForm)
        <x-admin.modal :title="$selectedId ? 'Edit kategori' : 'Tambah kategori'"><form wire:submit="save" class="space-y-4"><div><label for="category-household" class="mb-1 block text-sm font-bold text-slate-800">Keluarga</label><select id="category-household" wire:model.live="household_id" class="admin-select"><option value="">Pilih keluarga</option>@foreach($households as $household)<option value="{{ $household->id }}">{{ $household->name }}</option>@endforeach</select>@error('household_id')<p class="admin-error">{{ $message }}</p>@enderror</div><div><label for="category-name" class="mb-1 block text-sm font-bold text-slate-800">Nama kategori</label><input id="category-name" wire:model="name" class="admin-input">@error('name')<p class="admin-error">{{ $message }}</p>@enderror</div><div><label for="category-form-type" class="mb-1 block text-sm font-bold text-slate-800">Tipe</label><select id="category-form-type" wire:model.live="type" class="admin-select"><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select>@error('type')<p class="admin-error">{{ $message }}</p>@enderror</div><div><label for="category-parent" class="mb-1 block text-sm font-bold text-slate-800">Kategori induk <span class="font-normal text-slate-600">(opsional)</span></label><select id="category-parent" wire:model="parent_id" class="admin-select" @disabled(! $household_id || ! $type)><option value="">Tanpa induk</option>@foreach($parentCategories as $parent)<option value="{{ $parent->id }}">{{ $parent->name }}</option>@endforeach</select>@error('parent_id')<p class="admin-error">{{ $message }}</p>@enderror</div><div class="grid gap-4 sm:grid-cols-2"><div><label for="category-icon" class="mb-1 block text-sm font-bold text-slate-800">Ikon</label><input id="category-icon" wire:model="icon" class="admin-input" placeholder="Contoh: food"></div><div><label for="category-hue" class="mb-1 block text-sm font-bold text-slate-800">Hue warna</label><input id="category-hue" type="number" min="0" max="360" wire:model="hue" class="admin-input" placeholder="0 sampai 360"></div></div><div class="flex justify-end gap-2 pt-2"><button type="button" class="admin-button admin-button-secondary" wire:click="closeModal">Batal</button><button type="submit" class="admin-button admin-button-primary">Simpan kategori</button></div></form></x-admin.modal>
    @endif
    @if($showDelete)<x-admin.modal title="Hapus kategori"><p class="text-sm leading-6 text-slate-700">Hapus kategori <strong class="text-slate-950">{{ $selectedName }}</strong>? Data transaksi lama tetap ada, tetapi kategori tidak lagi tersedia.</p><div class="mt-5 flex justify-end gap-2"><button type="button" class="admin-button admin-button-secondary" wire:click="closeModal">Batal</button><button type="button" class="admin-button admin-button-danger" wire:click="delete">Hapus kategori</button></div></x-admin.modal>@endif
</div>
