<div>
    <x-admin.page-header title="Dompet" description="Periksa dompet pribadi dan bersama yang tersimpan." />
    <div class="admin-card overflow-hidden">
        <div class="border-b border-slate-100 px-4 py-4 sm:px-6"><h2 class="text-base font-extrabold text-slate-900">Semua dompet</h2><p class="mt-1 text-xs font-semibold text-slate-600">{{ $wallets->total() }} dompet ditemukan.</p></div>
        <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Nama</th><th>Keluarga</th><th>Ruang lingkup</th><th>Tipe</th><th>Saldo saat ini</th><th>Aksi</th></tr></thead><tbody>
        @forelse($wallets as $wallet)
            <tr><td class="font-bold text-slate-800">{{ $wallet->name }}</td><td class="text-sm text-slate-700">{{ $wallet->household?->name ?? '-' }}</td><td><span class="rounded-md bg-slate-100 px-2 py-1 text-xs font-bold text-slate-700">{{ $wallet->scope === 'shared' ? 'Bersama' : 'Pribadi' }}</span></td><td class="text-sm capitalize text-slate-700">{{ $wallet->type }}</td><td @class(['whitespace-nowrap text-sm font-extrabold', 'text-emerald-700' => $wallet->current_balance >= 0, 'text-rose-700' => $wallet->current_balance < 0])>Rp {{ number_format($wallet->current_balance, 0, ',', '.') }}</td><td><div class="flex flex-wrap gap-2"><button type="button" class="admin-button admin-button-secondary" wire:click="edit({{ $wallet->id }})">Edit</button><button type="button" class="admin-button admin-button-danger" wire:click="askDelete({{ $wallet->id }})">Hapus</button></div></td></tr>
        @empty
            <tr><td colspan="6" class="px-4 py-10 text-center text-sm font-semibold text-slate-600">Belum ada dompet.</td></tr>
        @endforelse
        </tbody></table></div><x-admin.pagination :items="$wallets" />
    </div>
    @if($showEdit)<x-admin.modal title="Edit dompet"><form wire:submit="update" class="space-y-4"><div><label for="wallet-name" class="mb-1 block text-sm font-bold text-slate-800">Nama dompet</label><input id="wallet-name" wire:model="name" class="admin-input">@error('name')<p class="admin-error">{{ $message }}</p>@enderror</div><div><label for="wallet-type" class="mb-1 block text-sm font-bold text-slate-800">Tipe</label><select id="wallet-type" wire:model="type" class="admin-select"><option value="cash">Tunai</option><option value="bank">Bank</option><option value="ewallet">E-wallet</option></select>@error('type')<p class="admin-error">{{ $message }}</p>@enderror</div><div class="flex justify-end gap-2 pt-2"><button type="button" class="admin-button admin-button-secondary" wire:click="closeModal">Batal</button><button type="submit" class="admin-button admin-button-primary">Simpan</button></div></form></x-admin.modal>@endif
    @if($showDelete)<x-admin.modal title="Hapus dompet"><p class="text-sm leading-6 text-slate-700">Hapus dompet <strong class="text-slate-950">{{ $selectedName }}</strong>? Pastikan data ini memang tidak dibutuhkan lagi.</p><div class="mt-5 flex justify-end gap-2"><button type="button" class="admin-button admin-button-secondary" wire:click="closeModal">Batal</button><button type="button" class="admin-button admin-button-danger" wire:click="delete">Hapus dompet</button></div></x-admin.modal>@endif
</div>
