<div>
    <x-admin.page-header title="Anggaran" description="Kelola batas pengeluaran per keluarga dan kategori.">
        <x-slot:actions><button type="button" class="admin-button admin-button-primary" wire:click="openCreate">Tambah anggaran</button></x-slot:actions>
    </x-admin.page-header>
    <div class="admin-card overflow-hidden">
        <div class="border-b border-slate-100 px-4 py-4 sm:px-6"><h2 class="text-base font-extrabold text-slate-900">Semua anggaran</h2><p class="mt-1 text-xs font-semibold text-slate-600">{{ $budgets->total() }} anggaran ditemukan.</p></div>
        <div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Keluarga</th><th>Kategori</th><th>Ruang lingkup</th><th>Periode</th><th>Nominal</th><th>Aksi</th></tr></thead><tbody>
        @forelse($budgets as $budget)
            <tr><td class="font-bold text-slate-800">{{ $budget->household?->name ?? '-' }}</td><td class="text-sm text-slate-700">{{ $budget->category?->name ?? '-' }}</td><td><span class="rounded-md bg-slate-100 px-2 py-1 text-xs font-bold text-slate-700">{{ $budget->scope === 'family' ? 'Keluarga' : 'Pribadi' }}</span></td><td class="text-sm text-slate-700">{{ $budget->period_month }}</td><td class="whitespace-nowrap text-sm font-extrabold text-slate-800">Rp {{ number_format($budget->amount, 0, ',', '.') }}</td><td><div class="flex flex-wrap gap-2"><button type="button" class="admin-button admin-button-secondary" wire:click="edit({{ $budget->id }})">Edit</button><button type="button" class="admin-button admin-button-danger" wire:click="askDelete({{ $budget->id }})">Hapus</button></div></td></tr>
        @empty
            <tr><td colspan="6" class="px-4 py-10 text-center text-sm font-semibold text-slate-600">Belum ada anggaran. Tambahkan anggaran untuk mulai mengatur batas pengeluaran.</td></tr>
        @endforelse
        </tbody></table></div><x-admin.pagination :items="$budgets" />
    </div>
    @if($showForm)
        <x-admin.modal :title="$selectedId ? 'Edit anggaran' : 'Tambah anggaran'"><form wire:submit="save" class="space-y-4"><div><label for="budget-household" class="mb-1 block text-sm font-bold text-slate-800">Keluarga</label><select id="budget-household" wire:model.live="household_id" class="admin-select"><option value="">Pilih keluarga</option>@foreach($households as $household)<option value="{{ $household->id }}">{{ $household->name }}</option>@endforeach</select>@error('household_id')<p class="admin-error">{{ $message }}</p>@enderror</div><div><label for="budget-category" class="mb-1 block text-sm font-bold text-slate-800">Kategori</label><select id="budget-category" wire:model="category_id" class="admin-select" @disabled(! $household_id)><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }} ({{ $category->type }})</option>@endforeach</select>@error('category_id')<p class="admin-error">{{ $message }}</p>@enderror</div><div class="grid gap-4 sm:grid-cols-2"><div><label for="budget-scope" class="mb-1 block text-sm font-bold text-slate-800">Ruang lingkup</label><select id="budget-scope" wire:model="scope" class="admin-select"><option value="family">Keluarga</option><option value="personal">Pribadi</option></select></div><div><label for="budget-period" class="mb-1 block text-sm font-bold text-slate-800">Periode</label><input id="budget-period" type="month" wire:model="period_month" class="admin-input">@error('period_month')<p class="admin-error">{{ $message }}</p>@enderror</div></div><div><label for="budget-amount" class="mb-1 block text-sm font-bold text-slate-800">Nominal anggaran</label><input id="budget-amount" type="number" min="1" wire:model="amount" class="admin-input" placeholder="Contoh: 1500000">@error('amount')<p class="admin-error">{{ $message }}</p>@enderror</div><div class="flex justify-end gap-2 pt-2"><button type="button" class="admin-button admin-button-secondary" wire:click="closeModal">Batal</button><button type="submit" class="admin-button admin-button-primary">Simpan anggaran</button></div></form></x-admin.modal>
    @endif
    @if($showDelete)<x-admin.modal title="Hapus anggaran"><p class="text-sm leading-6 text-slate-700">Hapus anggaran kategori <strong class="text-slate-950">{{ $selectedName }}</strong>?</p><div class="mt-5 flex justify-end gap-2"><button type="button" class="admin-button admin-button-secondary" wire:click="closeModal">Batal</button><button type="button" class="admin-button admin-button-danger" wire:click="delete">Hapus anggaran</button></div></x-admin.modal>@endif
</div>
